import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {MSWProvider} from './_component/MSWComponent';

// 런타임이 nodejs이고, 개발모드일 때
if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV === 'production') {
  const {server} = require('@/mocks/http')
  server.listen()
}

const geistSans = Geist({
  variable:'--font-geist-sans',
  subsets :['latin'],
});

const geistMono = Geist_Mono({
  variable:'--font-geist-mono',
  subsets :['latin'],
});

export const metadata: Metadata = {
  title:'Create Next App',
  description:'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <MSWProvider>
        {children}
      </MSWProvider>
      </body>
      </html>
  );
}
